plumier/plumier

packages/multipart/package.json
packages/multipart/src/index.ts
packages/plumier/test/integration/multipart/file-upload.spec.ts
yarn.lock

Fixing @plumier/multipart random error on windows / AppVeyor

---

docs/Action-Result.md
docs/Controller.md
docs/Facility.md
docs/Middleware.md
docs/refs/Error-Handling.md
packages/core/src/index.ts
packages/core/src/router.ts
packages/core/src/types.ts
packages/core/src/validator.ts
packages/multipart/src/index.ts
packages/plumier/src/facility.ts
packages/plumier/test/integration/application/__snapshots__/error-handling.spec.ts.snap
packages/plumier/test/integration/application/error-handling.spec.ts
packages/plumier/test/integration/authorization/jwt-auth.spec.ts
packages/plumier/test/integration/binder/binder.spec.ts
packages/plumier/test/integration/mongoose/unique-validator.spec.ts
packages/plumier/test/integration/multipart/file-upload.spec.ts
packages/plumier/test/integration/validation/__snapshots__/validation.spec.ts.snap
packages/plumier/test/integration/validation/custom-message.spec.ts
packages/plumier/test/integration/validation/decorator.spec.ts
packages/plumier/test/integration/validation/validation.spec.ts
website/sidebars.json

This PR contains fixes for:
* Custom global error handler to possibly catch framework errors #165 
* Unified error response format #168 
* New documentation for [error handling](https://plumierjs.com/docs/refs/error-handling) and [ActionResult](https://plumierjs.com/docs/action-result)

Custom Global Error Handler

---

packages/mongoose/src/index.ts
packages/plumier/test/integration/mongoose/mongoose.spec.ts

Fixing ObjectId conversion issue on non relational data

---

packages/core/src/types.ts
packages/plumier/test/integration/application/action-result.spec.ts
packages/plumier/test/integration/application/return-value.spec.ts

PR for #196  to acommodate multiple Set-Cookie header.
In order to pass the test the related test is edited without compromising on the context.

change setHeader and header type

---

packages/plumier/src/index.ts

export http status

---

packages/plumier/test/integration/social-login/__snapshots__/social-login.spec.ts.snap
packages/plumier/test/integration/social-login/social-login.spec.ts
packages/social-login/src/callback-view.ts
packages/social-login/src/index.ts
packages/social-login/src/middleware.ts
packages/social-login/src/provider/facebook.ts
packages/social-login/src/provider/github.ts
packages/social-login/src/provider/gitlab.ts
packages/social-login/src/provider/google.ts

Change Error login status into Failed

Enhance callback view using ActionResult

---

docs/refs/Mongoose-Helper.md
packages/mongoose/src/index.ts
packages/plumier/test/integration/mongoose/unique-validator.spec.ts

Mongoose uniqe fix

---

docs/Overview.md
docs/refs/Authorization.md
docs/refs/Validation.md
docs/tutorials/basic-sql/02-Create-Domain.md
docs/tutorials/basic-sql/07-Create-Local-Authentication.md
docs/tutorials/basic-sql/09-Securing-Domain.md
packages/core/readme.md
packages/jwt/readme.md
packages/mongoose/readme.md
packages/multipart/readme.md
packages/plumier/readme.md
packages/serve-static/readme.md
packages/social-login/readme.md
readme.md

This PR fixes all documentations and Readme.md files related to the new validation behaviour (optional by default). 
* Fixes all docs related to Validator docs and Authorization docs
* Fixes all issue related to Tutorials

docs: Fix documentation related to new validation behaviour

---

packages/core/src/validator.ts

Refactor validation process, to distinguish between synchronous validation and asynchronous validation.

refactor: Refactor validator to make it more readable

---

docs/refs/Social-Login.md
packages/social-login/package.json
packages/social-login/src/core.ts
packages/social-login/src/facebook.ts
packages/social-login/src/github.ts
packages/social-login/src/gitlab.ts
packages/social-login/src/google.ts
tests/social-login/__snapshots__/oauth2.spec.ts.snap
tests/social-login/__snapshots__/providers.spec.ts.snap
tests/social-login/oauth2-server.ts
tests/social-login/oauth2.spec.ts

This PR fixes the value returned by `@bind.oAuthToken()`. Now its returned all tokens not only the `access_token`

fix: Fix oAuthToken return all the provider tokens

---

packages/core/package.json
packages/mongoose/package.json
packages/multipart/package.json

```
packages/core/package.json
@types/koa  ^2.11.0  →  ^2.11.2 
tinspector  ^2.2.10  →   ^2.3.0 
tslib       ^1.10.0  →  ^1.11.1 
packages/mongoose/package.json
@types/mongoose   ^5.7.0  →  ^5.7.3 
mongoose         ^5.8.10  →  ^5.9.2 
packages/multipart/package.json
formidable  ^1.2.1  →  ^1.2.2 
```

chore: Upgrade dependencies

---

benchmark/options.ts
packages/core/src/application-pipeline.ts
tests/application/metaprogramming.spec.ts

Since #386 its possible to spread `Invocation` object. This causing significant drop performance. 
This PR fixes the performance issue.

fix: Fix performance issue caused by invocation update

---

packages/core/src/controllers-helper.ts
packages/core/src/controllers.ts
tests/behavior/generic-controller/generic-controller.spec.ts

feat: Add generic controller response transformer

---

packages/core/src/controllers.ts
packages/core/src/index.ts
packages/core/test/__snapshots__/export.spec.ts.snap
packages/swagger/src/transform/schema.ts
packages/typeorm/src/repository.ts
tests/behavior/mongoose/__snapshots__/mongoose-generic.spec.ts.snap
tests/behavior/typeorm/__snapshots__/typeorm-generic.spec.ts.snap

fix: Reverse property should not be included on response

---

packages/core/src/types.ts
tests/behavior/mongoose/__snapshots__/mongoose-generic.spec.ts.snap
tests/behavior/mongoose/mongoose-generic.spec.ts
tests/behavior/typeorm/__snapshots__/typeorm-generic.spec.ts.snap
tests/behavior/typeorm/typeorm-generic.spec.ts

fix: Fix issue unable to set property with null

---

website/docs/Controller.md
website/docs/Fundamentals.md
website/docs/Routing.md
website/sidebars.js
website/src/css/custom.css

docs: Add controller documentation

---

packages/mongoose/package.json
tests/behavior/mongoose/mongoose-generic.spec.ts

this issue https://github.com/Automattic/mongoose/issues/9684

chore: Upgrade to mongoose 5.11.7 to fix Model<T & Document> issue

---

packages/core/src/authorization.ts
packages/core/src/index.ts
packages/core/test/__snapshots__/export.spec.ts.snap
packages/jwt/src/index.ts
tests/behavior/authorization/jwt-auth.spec.ts
tests/behavior/authorization/policies/has-user-policy.ts
website/docs/Authorization.md

feat: Add global auth policy registry

---

packages/core/src/controllers-helper.ts
tests/behavior/generic-controller/__snapshots__/generic-controller.spec.ts.snap
tests/behavior/generic-controller/generic-controller.spec.ts
website/docs/Generic-Controller.md

feat: Add configuration to specify nested generic controller

---

packages/core/src/controllers-helper.ts
tests/behavior/generic-controller/__snapshots__/generic-controller.spec.ts.snap
tests/behavior/generic-controller/generic-controller.spec.ts

feat: Add feature to use multiple generic controller

---

packages/typeorm/src/repository.ts
tests/behavior/typeorm/typeorm-generic.spec.ts

fix: Fix error when inserting records with many to one without parent relation

---

packages/reflect/src/parser.ts

fix(reflect): acorn using latest ES version
