docs/refs/Mongoose-Helper.md, packages/core/src/application/validator.ts, packages/mongoose/src/index.ts, packages/plumier/test/integration/mongoose/mongoose.spec.ts, packages/plumier/test/integration/multipart/file-upload.spec.ts
This PR fixes broken `@plumier/mongoose` feature described on #158 using TypedConverter visitor extension.
=> Implement @plumier/mongoose broken ObjectId relational object

.vscode/launch.json, packages/core/src/middleware-pipeline.ts, packages/core/src/router.ts, packages/core/src/types.ts, packages/core/src/validator.ts, packages/plumier/src/application.ts, packages/plumier/src/facility.ts, packages/plumier/test/integration/application/middleware.spec.ts
Middleware pipeline now possible to call from inside the middleware itself. This feature useful when it is required to invoke specific controller's action from inside middleware. 
Signature 
```typescript
function pipe(ctx: Context, route?: RouteInfo, state?: any)
```
* `ctx` current request context
* `route` route infor that the action will be executed 
* `state` additional state added to the `ctx.state` property to prevent infinite call.
example: 
```typescript
class AnimalFacility extends DefaultFacility {
async initialize(app: Readonly<PlumierApplication>, routes: RouteInfo[]): Promise<void> {
app.use({
execute: async i => {
if (!i.context.state.isFallback && i.context.request.path === "/hello")
return await pipe(i.context, routes[0], { isFallback: true })
else
return i.proceed()
}
}) …
```
=> fix: Expose middleware pipeline

packages/core/src/index.ts, packages/core/src/middleware-pipeline.ts, packages/core/src/router.ts, packages/core/src/types.ts, packages/plumier/test/integration/application/middleware.spec.ts
Sometime its necessary to get the result of another controller including its middleware execution, from inside another controller or from a middleware. The real case for this function is create a redirect request without changing the URL.
Controller invoker execute the middleware pipeline to execute controller including its middleware, its returned `ActionResult` so it can be returned from inside the calling controller or middleware. 
```typescript
function invoke(ctx: Context, route: RouteInfo)
```
Parameters: 
* `ctx` the request context 
* `route` route info metadata of the controller will be invoked, route metadata information can be retrieved from `ctx.routes`
When called from inside middleware its necessary to check the context state to prevent infinite call loop. Plumier provide …
=> feat: Controller invoker

packages/core/src/middleware-pipeline.ts, packages/core/src/types.ts, packages/plumier/test/integration/serve-file/__snapshots__/history-api-fallback.spec.ts.snap, packages/plumier/test/integration/serve-file/history-api-fallback.spec.ts, packages/serve-static/src/index.ts
This PR fixes the History Api Fallback redirection issue #247 . It uses the new feature Controller Invoker #249 to forward the response without changing the URL.
=> fix: Fix history api fallback redirection issue

packages/core/src/binder.ts, packages/core/src/decorator.bind.ts, packages/core/src/index.ts, packages/plumier/test/integration/binder/binder.spec.ts
This PR expose name of each parameter binding decorator. Previously it was impossible to identify which decorator was a parameter applied. 
```typescript
class AnimalController {
@route.get()
get(@bind.header("ip") ip: string) {
}
}
const meta = reflect(AnimalController)
console.log(meta.methods[0].parameters[0].decorators[0])
```
The result : 
```
{ type: 'ParameterBinding', process: [Function], name: 'header' }
```
Its now possible to distinguish between `@bind.header()`, `@bind.body()`, `@bind.cookie()` etc from its `name` property.
=> fix: Expose binder name on BindingDecorator

.github/workflows/publish-canary.yml, docs/extends/Custom-Authorization.md, packages/core/src/authorization.ts, packages/core/src/types.ts, packages/plumier/test/integration/jwt/jwt-auth.spec.ts
This PR contains fix that allows sync and async callback function on custom authorization.
Can be used for simple authorization.
```typescript 
@authorize.custom(x => x.user.userId === 1234)
```
Useful when the callback function need to do some long running operation such as database call etc. 
```typescript 
@authorize.custom(async x => {
const user = await UserModel.findById(x.user.userId)
return user.active && x.user.role === "User"
})
```
=> fix: Allow sync or async callback function on custom authorization

docs/extends/Custom-Validator.md, jest.config.js, packages/core/package.json, packages/core/src/types.ts, packages/core/src/validator.ts, packages/plumier/test/integration/validation/__snapshots__/validation.spec.ts.snap, packages/plumier/test/integration/validation/validation.spec.ts
This PR fixes the need of async function on custom validator.  
Can be used as simple value validation
```typescript
@val.custom(val => val < 18 ? "Must be 18+" : undefined)
```
Can be used as validation required long running process 
```typescript 
@val.custom(async val => {
const coupon = await CouponModel.findOne({ id : val})
if(!coupon.active) return "Coupon is not active"
})
```
=> fix: Allow sync or async callback function on custom validator

docs/Overview.md, docs/tutorials/basic-sql/08-Securing-Routes.md
Fix tutorial uses `parameter` property of the `AuthorizeMetadataInfo`.  #261 remove some parameters that make the tutorial unappropriate
=> docs: Fix tutorial match with exposed validator info property

packages/plumier/test/integration/social-login/__snapshots__/social-login.spec.ts.snap, packages/plumier/test/integration/social-login/social-login.spec.ts, packages/social-login/src/provider/google.ts
This PR fix issue causing `GoogleProvider` (the callback) doesn't returned user email on the bound login status `@bind.loginStatus()`.
=> fix: Fix Google oAuth endpoint scope to include email

packages/core/src/validator.ts, packages/plumier/test/integration/validation/__snapshots__/validation.spec.ts.snap, packages/plumier/test/integration/validation/validation.spec.ts
This PR enables Plumier to treat custom validator applied as a class scope decorator like example below:
```typescript
function checkConfirmPassword() {
return val.custom( x => {
if(x.password !== x.confirmPassword)
return val.result("confirmPassword", "Password is not the same")
})
}
@domain()
// apply custom validator as class decorator
@checkConfirmPassword()
class User {
constructor(
public password: string,
public confirmPassword: string
) { }
}
```
=> fix: Fix custom validator can't be applied as class level decorator

packages/social-login/src/provider/github.ts
This PR fixes GitHub profile properties based on GitHub documentation [here](https://developer.github.com/v3/users/#response)
```
{
"login": "octocat",
"id": 1,
"node_id": "MDQ6VXNlcjE=",
"avatar_url": "https://github.com/images/error/octocat_happy.gif",
"gravatar_id": "",
"url": "https://api.github.com/users/octocat",
"html_url": "https://github.com/octocat",
"followers_url": "https://api.github.com/users/octocat/followers",
"following_url": "https://api.github.com/users/octocat/following{/other_user}",
"gists_url": "https://api.github.com/users/octocat/gists{/gist_id}",
"starred_url": "https://api.github.com/users/octocat/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/octocat/subscriptions",
"organizations_url": "https://api.github.com/users/octocat/orgs", …
```
=> fix: Fix GitHub profile properties based on GitHub docs

packages/core/package.json, packages/core/src/decorator.authorize.ts, packages/core/src/decorator.bind.ts, packages/plumier/test/integration/application/restful.spec.ts, packages/plumier/test/integration/authorization/jwt-auth.spec.ts, packages/plumier/test/integration/binder/binder.spec.ts, packages/plumier/test/integration/mongoose/mongoose.spec.ts, packages/plumier/test/integration/mongoose/unique-validator.spec.ts, packages/plumier/test/integration/social-login/controller/facebook-controller.ts, packages/plumier/test/integration/social-login/controller/github-controller.ts, packages/plumier/test/integration/social-login/controller/gitlab-controller.ts, packages/plumier/test/integration/social-login/controller/google-controller.ts, packages/plumier/test/integration/social-login/social-login.spec.ts, packages/plumier/test/integration/validation/__snapshots__/validation.spec.ts.snap, packages/plumier/test/integration/validation/validation.spec.ts, packages/social-login/src/middleware.ts
This PR change the validation behaviour which was required by default for each property / parameter changed to optional by default. 
This behaviour required to keep compatibility with other web framework and validation library.
If you have domain like below: 
```typescript
@domain()
class Animal {
constructor(
@val.required(),
public id:number,
@val.required()
public name: string,
public dateOfBirth: string
) { }
}
```
It's now possible to omit the `dateOfBirth` property because its now optional by default. 
```
{ "id": 1234, "name": "Mimi" }
```
=> fix: Validation behavior is optional by default

packages/core/src/types.ts, packages/core/src/validator.ts, packages/mongoose/src/index.ts
This PR fixes typedconverter `@val` augmentation issue on `@plumier/core`. This issue make `@val.custom()` and `@val.result()` can't be detected from other package, for example `@plumier/mongoose`
=> fix: Fix @val.custom not being detected on @plumier/mongoose

docs/Middleware.md, packages/core/src/router.ts, packages/plumier/test/integration/application/query.spec.ts
This PR allows `ctx.query` and `ctx.request.query` accessible insensitively. 
for example giving the path `/path?animalId=123` can be accessed using:
```typescript
ctx.query.animalid
ctx.query.AnimalId
ctx.query.ANIMALID
ctx.query["animalid"]
ctx.query["AnimalId"]
ctx.query["ANIMALID"]
```
=> fix: Fix query case sensitivity issue on ctx.query and ctx.request.query

packages/core/src/authorization.ts, packages/core/src/binder.ts, packages/core/src/decorator.bind.ts, packages/core/src/index.ts, packages/core/src/types.ts, packages/plumier/src/index.ts
All custom components (middleware, validator, binder, authorizer) now has naming convention `CustomXXX` for object type and `CustomXXXFunction` for function type.
Alias added: 
```
CustomMiddleware 
CustomMiddlewareFunction
CustomBinderFunction
CustomAuthorizer
CustomAuthorizerFunction
AuthorizerContext
CustomValidator 
CustomValidatiorFunction
ValidatorContext
```
=> refactor: Add new types to follow the type convention

package.json, packages/plumier/src/facility.ts, packages/plumier/src/index.ts, packages/plumier/test/integration/application/cors.spec.ts
CORS now disabled by default, and configurable from `WebApiFacility`. 
```typescript
// to use default setting 
app.set(new WebApiFacility({ cors: true }))
// to override default configuration
app.set(new WebApiFacility({ cors: { origin: "http://plumierjs.com" } }))
```
=> fix: CORS is disabled by default

packages/core/src/application-pipeline.ts, packages/core/src/router.ts, packages/core/src/validator.ts, packages/plumier/test/benchmark/options.ts, packages/plumier/test/benchmark/server/express-jwt.ts, packages/plumier/test/benchmark/server/express.ts, packages/plumier/test/benchmark/server/koa-jwt.ts, packages/plumier/test/benchmark/server/koa.ts
This PR uses new logic to chain execution of middleware `Invocation`. Previously the middleware chain generated dynamically on every request, this technique quite fast but when number of middlewares increase it will cause scalability issue. 
The new logic cached (compile) the execution chain using linked list than reuse it on each request.
=> fix: Tweak middleware pipeline for performance and scale

.travis.yml, appveyor.yml, packages/core/readme.md, packages/jwt/readme.md, packages/mongoose/readme.md, packages/multipart/readme.md, packages/plumier/readme.md, packages/serve-static/readme.md, packages/social-login/readme.md, readme.md
Drop test environment on Node.js 8 since some dependencies required Node.js >= 10
=> chore: Drop tests environment on Node.js 8 and update appropriate docs

packages/core/src/types.ts, packages/plumier/test/integration/action-result/__snapshots__/action-result.spec.ts.snap, packages/plumier/test/integration/action-result/action-result.spec.ts
This PR exposes `headers` and `cookies` property of `ActionResult` object.
```typescript
const result = new ActionResult()
// headers
result.headers
// cookies
result.cookies
```
=> fix: Expose headers and cookies on ActionResult

docs/refs/Authorization.md, docs/refs/Mongoose-Helper.md, docs/refs/Social-Login.md, packages/jwt/src/index.ts, packages/mongoose/src/index.ts, packages/social-login/src/core.ts, packages/social-login/src/facebook.ts, packages/social-login/src/github.ts, packages/social-login/src/gitlab.ts, packages/social-login/src/google.ts, tests/authorization/__snapshots__/jwt-auth.spec.ts.snap, tests/authorization/jwt-auth.spec.ts, tests/mongoose/mongoose.spec.ts, tests/social-login-web/__snapshots__/facebook.spec.ts.snap, tests/social-login-web/__snapshots__/github.spec.ts.snap, tests/social-login-web/__snapshots__/gitlab.spec.ts.snap, tests/social-login-web/__snapshots__/google.spec.ts.snap, tests/social-login-web/facebook.spec.ts, tests/social-login-web/github.spec.ts, tests/social-login-web/gitlab.spec.ts, tests/social-login-web/google.spec.ts
With this PR some Facility now automatically load default configuration from environment variable: 
| Facility                | Environment Variable                                     |
| ----------------------- | -------------------------------------------------------- |
| `MongooseFacility`      | `PLUM_MONGODB_URI`                                       |
| `JwtAuthFacility`       | `PLUM_JWT_SECRET`                                        |
| `FacebookOAuthFacility` | `PLUM_FACEBOOK_CLIENT_ID`  `PLUM_FACEBOOK_CLIENT_SECRET` |
| `GoogleOAuthFacility`   | `PLUM_GOOGLE_CLIENT_ID`    `PLUM_GOOGLE_CLIENT_SECRET`   |
| `GitHubOAuthFacility`   | `PLUM_GITHUB_CLIENT_ID`    `PLUM_GITHUB_CLIENT_SECRET`   |
| `GitLabOAuthFacility`   | `PLUM_GITLAB_CLIENT_ID`    `PLUM_GITLAB_CLIENT_SECRET`   |
=> fix: Load default configuration from environment variable

packages/core/src/decorator.bind.ts, tests/binder/__snapshots__/binder.spec.ts.snap, tests/binder/binder.spec.ts, tests/validation/__snapshots__/validation.spec.ts.snap, tests/validation/validation.spec.ts
This PR added support binding FormFile using decorator via `@bind.formFile()` 
```typescript
class AnimalController {
@route.post()
save(@bind.formFile("file") data: FormFile) {
return { name: data.name, type: data.type }
}
}
```
=> feat: Add form file binding decorator

packages/core/package.json, packages/core/src/route-analyzer.ts, packages/core/src/validator.ts, packages/mongoose/src/index.ts, tests/binder/__snapshots__/binder.spec.ts.snap, tests/binder/binder.spec.ts
An input file set with `multiple` property required the appropriate bound parameter uses Array of `FormFile`. This run well when number of files sent more than one, but cause problem when only single file sent. 
```html
<form method="POST" enctype="multipart/form-data" action="/animal/save">
<input type="file" name="file" value="Select file" multiple/>
<input type="submit" value="Upload"/>
</form>
```
The appropriate action:
```typescript
export class AnimalController {
@route.post()
save(file: FormFile[]) {
return response.redirect("/")
}
}
```
Above code will not working when only single file sent to server. This issue caused by `tinspector` module failed parse the type information of the Array parameter if no type override provided.
=> fix: Multiple FormFile issue with guestArrayElement

packages/core/src/types.ts, tests/binder/__snapshots__/binder.spec.ts.snap, tests/binder/binder.spec.ts
This PR fixes issue when `FileForm` defined as array and causing Route Analysis complaining about parameter binding being skipped
```
warning PLUM1006: Parameter binding skipped because array field without @array() decorator found in (AnimalController.save.file)
```
This PR change `FileForm` as a class so it possible to override the array type to prevent the warning. 
```typescript
export class AnimalController {
@route.post()
save(@reflect.type([FormFile]) file: FormFile[]) {
console.log(file.length)
return response.redirect("/")
}
}
```
=> fix: Fix array of FileForm causes route analysis warning

.gitignore, packages/core/src/index.ts, packages/core/src/types.ts, packages/plumier/src/index.ts, tests/action-result/action-result.spec.ts
This PR fixes `ActionResult` method `setCookie` to accept a cookie object `HttpCookie` like below: 
```typescript
return ActionResult({})
.setCookie({ key: "theName", value: "lorem ipsum" })
```
Its also possible to set array of `HttpCookie`
```typescript
return ActionResult({})
.setCookie([
{ key: "theName", value: "lorem ipsum" },
{ key: "otherName", value: "lorem ipsum",  option: { sameSite: "lax" } }
])
```
Its also possible to remove cookies using multiple names
```typescript
return ActionResult({})
.setCookie([
{ key: "theName" },
{ key: "otherName" }
])
```
=> fix: Fix ActionResult to accept HttpCookie interface and Array

docs/refs/Social-Login.md, packages/social-login/src/core.ts, tests/social-login/__snapshots__/oauth2.spec.ts.snap, tests/social-login/oauth2.spec.ts
This PR adds 2 more parameter binding to bind social media login data. 
| Decorator | Description |
| - | - |
| `@bind.oAuthUser()` | Bind generalized social media login user of type `OAuthUser` |
| `@bind.oAuthProfile()` | Bind the raw social media user profile | 
| `@bind.oAuthToken()` | Bind social media auth token |
=> feat: Add social media profile and access token parameter binding

packages/core/src/types.ts, packages/plumier/src/application.ts, tests/application/__snapshots__/basic.spec.ts.snap, tests/application/basic.spec.ts
This PR add `listen` method to easily listen to port without having to us `Koa` instance. 
```typescript
new Plumier()
.use(new WebApiFacility())
.listen()
```
`listen` method accepts port value such as `listen(8080)` but first it will check for environment variable `PLUM_PORT`.
=> feat: Add listen method to listen port form Plumier instance

packages/core/src/types.ts, packages/plumier/src/application.ts, packages/plumier/src/facility.ts, tests/application/__snapshots__/basic.spec.ts.snap, tests/application/basic.spec.ts
When behind reverse proxy, some request information might forwarded in header information such as: 
* X-Forwarded-For : the request IP address 
* X-Forwarded-Proto: the request protocol
* X-Forwarded-Host: the request host
This issue occurs in some hostings such as Heroku. To fix this issue, the proxy header need to be configured (trusted).
```typescript
new Plumier()
.set(new WebApiFacility({ trustProxyHeader: true })
```
=> fix: Add configuration to accept proxy headers

packages/plumier/src/facility.ts, tests/application/__snapshots__/basic.spec.ts.snap, tests/application/basic.spec.ts
This PR adds logic to redirect all HTTP request become HTTPS request. Enable this feature from `WebApiFacility` constructor.
Note that this feature only work when `NODE_ENV` set to production. 
```
new Plumier()
.set(new WebApiFacility({ forceHttps: true })
```
=> feat: Add force https

packages/plumier/src/binder.ts, packages/plumier/src/index.ts, tests/binder/binder.spec.ts
This PR adds feature to bind raw body into parameter. 
By default this feature is disabled, enable this by set the `includeUnparsed` in the `WebApiFacility` configuration like below: 
```
new Plumier()
.set(new WebApiFacility({ bodyParser: { includeUnparsed:true }}))
```
Use it like other decorator based parameter binding like below
```
class AnimalController {
@route.post()
save(@bind.rawBody() body: any) {
}
}
```
=> feat: Add rawBody parameter binding

packages/core/src/route-virtual.ts, packages/core/src/types.ts, packages/plumier/src/application.ts, tests/route-generator/__snapshots__/virtual-route.spec.ts.snap, tests/route-generator/virtual-route.spec.ts
This PR add function to register route programmatically from `Facility.initialize` method. 
```typescript
class MyFacility extends DefaultFacility {
async initialize(app: Readonly<PlumierApplication>, routes:RouteInfo[], vroutes:VirtualRouteInfo[]) {
vroutes.push({method: "get", url: "/route/route", access: "Public", className: "MyFacility"})
}
}
```
=> feat: Add function to register virtual route programmatically

docs/Extend.md, docs/extends/Custom-Authorization.md, packages/core/src/application-pipeline.ts, packages/core/src/authorization.ts, packages/core/src/decorator.ts, packages/core/src/types.ts, packages/core/src/validator.ts, tests/application/__snapshots__/metaprogramming.spec.ts.snap, tests/application/metaprogramming.spec.ts, tests/middleware/__snapshots__/middleware.spec.ts.snap, tests/middleware/middleware.spec.ts
Request metadata contains information about Controller & Action metadata useful for metaprogramming. 
Request metadata accessible from `Invocation`, `ValidationContext` and `AuthorizerContext`. 
```typescript
// Invocation
const customMiddleware:CustomMiddlewareFunction = ({ metadata, proceed }) => {
if(metadata.controller.name === "AnimalController")
return proceed()
else 
throw new HttpStatusError(404)
}
// ValidatorContext
const customValidation: CustomValidatorFunction = (val, { metadata }) => { 
// process metadata
}
// AuthorizerContext
const customAuthorizer: CustomAuthorizerFunction = ({ metadata, ctx }) => {
// process metadata
}
```
=> feat: Expose metadata property to facilitate metaprogramming

docs/refs/Mongoose-Helper.md, packages/mongoose/readme.md, packages/mongoose/src/generator.ts, packages/mongoose/src/types.ts, tests/behavior/mongoose/__snapshots__/dockify.spec.ts.snap, tests/behavior/mongoose/dockify.spec.ts, tests/behavior/mongoose/mongoose.spec.ts
`Dockify<T>` is an advanced TypeScript type, it converts all Property of `T` inherit from `Object` into mongoose `Document`. For example: 
```typescript 
class Child {
constructor(
public name:string
){}
}
class Parent {
constructor(
public child:Child
){}
}
let parent:Dockify<Parent>
// child property converted into `Child & mongoose.Document` 
// thus its possible access document properties/method like below
parent.child._id
parent.child.save()
```
`Dockify<T>` provide syntax sugar to access ref (populate) properties, while keep entity definition POJO (clean from Mongoose specific types). 
> **CAVEAT**: Dockify will treat all properties with custom type as Document, thus for non ref (populate) property will keep inferred as `Document`.
=> fix: Fix mongoose helper document type inference
